[M] RR: Create individual review tile ETC: 11/20 (Ticket#46)
Quidditch-Queue-Handlers/FEC-Project-Atelier pull request #37
Opened 2023-11-25 17:22 UTC by squeakypickles33

Quite a bit of small changes. Also got the thumbnail to pop up full screen

2023-11-25 22:38 UTC, burhan-syed requested changes

2023-11-25 22:38 UTC, burhan-syed commented on client/src/components/RatingsAndReviews/Review.jsx
I see you're using native JS with getElementById to do things like changing the image src for photo or adding / removing classes to make modals visible. 
This works here but breaks some of the encapsulation of React components. Because we're selecting elements by Id we will have to be aware of the Ids anytime we use this getElementById pattern so we don't run into unintended behavior elsewhere.
This is also a more 'imperative' way of coding as opposed to the declarative style React encourages. Instead, we could track the src of the bigPhoto in state and change that state as needed, for example
```
const [bigPhotoSrc, setBigPhotoSrc] = useState(""); 
...
<img src={bigPhotoSrc} />
```

The modal toggle similarly should be handled in react state. You could either toggle the style or whether the whole modal is rendered. For example
```
const [showModal, setShowModal] = useState(false); 
...
{showModal && <div className="rr-modal">...</div>}
//or
<div className={"rr-modal " + showModal ? "rr-modal-visible" : ""}>...</div>
```
This way we don't have to worry about global Ids and the component just controls its own state. 

If there are things that can't be controlled by state and you need reference to that HTML element I would use [useRef](https://react.dev/reference/react/useRef#manipulating-the-dom-with-a-ref) instead.

2023-11-26 15:48 UTC, squeakypickles33 commented on client/src/components/RatingsAndReviews/Review.jsx
That's perfect, I was thinking of using react states for these but felt like I was using too many but I need to remove that from my thought process. Thank you for the clarification and I will fix these

2023-11-26 19:17 UTC, burhan-syed commented on client/src/components/RatingsAndReviews/Review.jsx
> +    setShowFullBody(!showFullBody);
When updating state based on previous state I would recommend using an updater function. 
See https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state

2023-11-26 19:19 UTC, burhan-syed approved these changes
Overall I see you updated your code to use state instead of direct DOM manipulation with getElementById. Everything looks good to merge but I left a comment on updating state you may want to review. I'll leave this unmerged incase you want to make those changes.

2023-11-26 19:28 UTC, merged